### ISSUE TITLE
Private embassy URL exposed

### ISSUE THREAD

**Issue by benburton** [abramenal/embassy-appointment#1]
Hello,

I thought you should know that you've got the private URL for your embassy appointment exposed in a public repository. This is probably a bad thing.

I came across this repository while struggling with [this issue](https://github.com/abramenal/cypress-file-upload/issues/214). If you could take a look, it would be much appreciated.

**Comment by abramenal** [comment]
Hi @benburton 
Thanks for submitting the issue!
I think this URL is public since it was shared on some of embassy's public pages, all sensitive info is stored in ENV variables 😉 

As for mentioned issue, Joseph will be maintaining the issue, this evening I gave him access to the repo.

**Comment by benburton** [comment]
Thanks!
